project:
  type: default
  output-dir: _site
  render:
    - index.qmd
    - open-science/index.qmd
    - statistical-inference/index.qmd

lang: en-GB

format:
  revealjs:
    theme: simple
    lightbox: true
    embed-resources: true
    slide-number: true
    show-slide-number: all
    width: 1280
    height: 720
    margin: 0.08
    incremental: true
    transition: fade
    transition-speed: default
    fig-align: center
    code-line-numbers: false
    highlight-style: github

execute:
  echo: false
  warning: false
  message: false
  cache: false
